# config
cover: /img/bg_img.jpg
#logo: /img/logo.png
top_saying:
- title: 久在樊笼里，何时返自然
bottom_saying:
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs


#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/aruis
twitter: https://twitter.com/aruis
weibo: http://weibo.com/aruis


# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
